.github/CODEOWNERS, .github/workflows/auto-approve.yml, .github/workflows/auto-assignee-label.yml
=> [chore] workflow 관련

.github/workflows/deploy-integration.yml, .github/workflows/deploy-target.yml, .gitignore
- @evenway2025 계정으로 Vercel 배포를 수행합니다.
| 기능 | 스크린샷 |
=> [chore] Deploy Vercel Workflow

.github/workflows/deploy-integration.yml, .github/workflows/deploy-target.yml, .gitignore
- @evenway2025 로 Vercel 배포를 위한 Workflow 추가
| 기능 | 스크린샷 |
=> [chore] Vercel Workflow 추가

scripts/build.sh
- @evenway2025로 Vercel 배포를 위한 누락된 build.sh 추가
| 기능 | 스크린샷 |
=> [chore] Vercel Workflow 수정

scripts/build.sh
- Vercel Deploy 을 위한 누락된 build.sh 추가
| 기능 | 스크린샷 |
=> [chore] Vercel Workflow 수정

.github/workflows/deploy-integration.yml, README.md, cspell.json, package.json, pnpm-lock.yaml, scripts/build.sh, scripts/https-local-server.js, scripts/setup.sh
- Custom Local Server Https 를 적용합니다.
- 레포지토리 네임이 변경됨에 따라 배포 CI/CD 를 수정합니다.
=> [chore] Custom Local Dev Server

.github/workflows/pr-comment.yml, .github/workflows/pr-reivew.yml
closes #23 
* PR 리뷰 요청 시 슬랙으로 알림을 보내는 작업을 수행합니다.
* PR 리뷰에 대한 세부 정보를 포함한 Slack 알림을 보냅니다.
=> [chore] PR Comment 슬랙 알림과 PR Reviewer 알림 추가

src/shared/ui/Avatar/avatar.tsx, src/shared/ui/Avatar/index.tsx, src/shared/ui/Input/index.tsx, src/shared/ui/Input/input.tsx, src/shared/ui/Toast/index.tsx, src/shared/ui/appbar.tsx, src/shared/ui/button.tsx, src/shared/ui/card.tsx, src/shared/ui/footer.tsx, src/shared/ui/header.tsx, src/shared/ui/img.tsx, src/shared/ui/list/index.tsx, src/shared/ui/list/wrappedList.tsx, src/shared/ui/tab.tsx, src/shared/ui/thumbnail.tsx, src/shared/ui/typography/index.tsx
- 공통 컴포넌트 use client 일괄 지정
- 클라이언트 컴포넌트로 활용되어야 하는 것 한해서 지정
=> [Refactor] 공통 컴포넌트 use client 지정

src/shared/ui/appbar.tsx
- Appbar padding 20px 로 일괄 지정 (디자인 수정사항 반영)
=> [Design] Appbar padding 20px 로 일괄 지정

src/app/page.tsx, src/shared/ui/Navigation/icons/MyCardIcon.tsx, src/shared/ui/Navigation/icons/ReceivedCardIcon.tsx, src/shared/ui/Navigation/icons/SettingIcon.tsx, src/shared/ui/Navigation/index.tsx
=> [feat] navbar 구현

src/features/multi-step-form/components/AvartarImg.tsx, src/features/multi-step-form/hooks/queries/useCreateCard.ts, src/features/multi-step-form/schema/index.ts, src/features/multi-step-form/ui/careerForm/fourthStep.tsx, src/features/multi-step-form/ui/careerForm/secondStep.tsx
=> debug (#112)

src/app/globals.css, src/features/setting/ui/index.tsx, src/features/setting/ui/privacyTerms.tsx
* 스타일: 다크모드, 라이트 모드 구분제거
* 일관성있는 약관 스타일 적용
=> fix: 다크모드, 라이트 모드 제거

src/features/auth/login/ui/LoginButton.tsx, src/features/auth/login/utils/nativeBridge.ts
관련이슈 close #122 
* 구글로그인을 접근 할 시 웹뷰 403 정책으로인해, 브릿지 코드 적용
=> [feat] 구글 로그인 브릿지 적용

src/app/api/auth/callback/[provider]/page.tsx, src/app/api/auth/callback/[provider]/route.ts, src/features/auth/login/config/authConfig.ts, src/shared/apis/client.ts, src/shared/apis/server.ts
- Apple Login 은 request body에 code가 담겨오는듯?
| 기능 | 스크린샷 |
=> [Refactor] apple login 방식 수정

pnpm-lock.yaml
=> [chore] update pnpm lock

src/features/home/hooks/queries/useCardQuery.ts
=> [Hotfix] disable api my fetching temporary

src/features/home/hooks/queries/useCardQuery.ts, src/features/share/hooks/queries/useCardQuery.ts
=> [hotfix] temporary disable react query hook - my/card

src/features/card-detail/hooks/query/useCardDetailQuery.ts, src/features/card-detail/mocks/myCardDetail.ts, src/shared/ui/Toast/index.tsx
임시 데이터 설정 및 토스트 error svg 경로  수정
임시 데이터 설정 및 토스트 error svg 경로  수정
=> ♻️ refactor : 임시 데이터 설정 및 토스트 error svg 경로  수정

src/features/auth/login/config/authConfig.ts
=> 🐛 HotFix: 로그인 isProd 플래그 수정

src/app/layout.tsx, src/features/auth/login/apis/getToken.ts, src/features/auth/login/types/auth.ts, src/features/multi-step-form/components/AvartarImg.tsx, src/features/multi-step-form/config/index.ts
* 동적 메타 태그 최상단 layout 적용
* 카드 생성 - 이미지 업로드 10MB 확장
=> [feat] 메타 태그 적용

src/features/card-detail/mocks/myCardDetail.ts, src/features/card-detail/ui/cardTabs.tsx, src/features/card-detail/ui/sns.tsx, src/features/card-detail/utils/filteredTabs.ts, src/shared/ui/bottomModal/memoInput.tsx
명함 상세 페이지 2차 QA 작업
- 바텀시트 - 간격확인
- 한 줄 메모 - 제출 버튼 추가
- sns label - 언더바 제거 , 스페이스 추가
- tab 노출 기준 수정
=> [feat] 명함 상세 페이지 2차 QA 작업

src/app/globals.css, src/app/share/page.tsx, src/features/card-detail/config/jobs-config.ts, src/features/card-detail/ui/cardDetailHeader.tsx, src/features/home/containers/CardContainer.tsx, src/features/onboarding/config/slides.tsx, src/features/share/containers/QrContainer.tsx
=> [develop] home refactor detail, share page

src/features/home/containers/CardContainer.tsx
=> refactor: silde align center

next.config.mjs, src/app/(received)/received/choose/page.tsx, src/app/(received)/received/page.tsx, src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TagBox.tsx, src/features/received/ui/emptyCard.tsx, src/features/received/ui/foldersList.tsx, src/features/received/ui/intellibanner.tsx, src/features/received/ui/lottieLoading.tsx, src/features/received/ui/receivedCard.tsx, src/features/received/ui/receivedCardView.tsx, src/shared/ui/appbar.tsx, src/shared/ui/thumbnail.tsx
#170 [Fix] 명함 생성, 받은 명함 QA 2차
| 기능 | 스크린샷 |
=> [Fix] 명함 생성, 받은 명함 QA 2차

src/features/card-detail/ui/cardDetailHeader.tsx, src/features/home/components/BusinessCard/Card.tsx, src/features/home/components/BusinessCard/CardTag.tsx, src/features/home/containers/CardContainer.tsx, src/features/home/types/index.ts, src/features/multi-step-form/ui/careerForm/fourthStep.tsx, src/features/received/ui/receivedCard.tsx, src/features/share/components/Background.tsx, src/features/share/components/JobLogo.tsx, src/features/share/components/QrInfo.tsx, src/features/share/components/ShareButton.tsx, src/features/share/components/ShareCard.tsx, src/features/share/components/ShareCardTag.tsx, src/features/share/containers/BackgroundContainer.tsx, src/features/share/containers/QrContainer.tsx
=> [feat] Job 타입 수정

src/features/setting/hooks/useLogout.ts, src/features/setting/ui/index.tsx, src/shared/components/seo/generateMetaData.tsx, src/shared/hooks/useCookies.ts, src/shared/ui/dialog/wrappedDialog.tsx, src/shared/utils/cookies.ts, src/shared/utils/handleAxiosError.ts, src/shared/utils/sleep.ts
* 회원 로그아웃 구현
* 공통 유틸 함수 쿠키,  쿠키 hooks 구현
* 비동기 처리시 대기를 위한 sleep 구현
* 모달 자동 포커싱 제거
=> [feat] 회원 로그아웃 구현

src/features/auth/login/ui/LoginFeature.tsx, src/features/login/components/Background.tsx, src/features/login/containers/LoginBackgroundContainer.tsx
* 로그인 페이지 가로 스크롤 방지
| 기능 | 스크린샷 |
=> 💄 Style: 로그인 페이지 고정 이미지 가변적으로 수정

src/features/auth/login/ui/LoginButton.tsx, src/features/home/components/BusinessCard/Card.tsx, src/features/home/containers/CardContainer.tsx, src/shared/utils/handleAxiosError.ts
=> [Refactor/home link] 홈 버그

src/features/home/containers/CardContainer.tsx, src/features/home/containers/ClipboardContainer.tsx
=> 공유하기 임시 버튼으로 수정

src/features/home/containers/CardContainer.tsx
=> refactor: 카드 추가에는 공유 버튼 제거 및 스타일 조정

src/features/home/containers/CardContainer.tsx
=> refactor: 세부 직업 표시

src/features/card-detail/mocks/myCardDetail.ts, src/features/card-detail/ui/projects.tsx, src/shared/ui/postThumbnail.tsx
작성한 글 텍스트 길이 수정
작성한 글 텍스트 길이 수정
=> [refactor] 작성한 글 텍스트 길이 수정

src/features/card-detail/mocks/myCardDetail.ts, src/features/card-detail/ui/projects.tsx, src/features/home/components/BusinessCard/Card.tsx, src/features/home/containers/CardContainer.tsx, src/features/share/components/ShareCard.tsx, src/features/share/container/ShareCardContentContainer.tsx, src/shared/ui/img.tsx, src/shared/ui/postThumbnail.tsx
=> [refactor] 홈 화면 수정

src/features/multi-step-form/ui/careerForm/thridStep.tsx
=> refactor : 작성한 글 , 대표 프로젝트 placeholder 수정

src/app/share/page.tsx, src/features/card-detail/ui/cardDetailHeader.tsx, src/features/home/components/BusinessCard/Card.tsx, src/features/share/components/ShareCard.tsx
=> refactor: error image

src/features/share/components/ShareButton.tsx
=> refactor: navigator link

src/features/card-detail/ui/cardDetailHeader.tsx, src/features/home/components/BusinessCard/Card.tsx, src/features/share/components/ShareCard.tsx
=> refactor: update image src when inital state changed

src/features/received/ui/receivedCardView.tsx, src/shared/ui/appbar.tsx
=> ✨ Feat: 폴더 이름 설정, 폴더 추가 바텀 시트에 버튼 추가

src/features/auth/login/utils/nativeBridge.ts, src/features/multi-step-form/components/AvartarImg.tsx
* 카메라 권한 승인 및 업로드 웹뷰 브릿지 기능 추가
| 기능 | 스크린샷 |
=> [feat] 카드 생성 - 웹뷰 지원 구현

src/features/multi-step-form/components/AvartarImg.tsx
=> ✨ Feat: 카메라 브릿지, 드롭다운 추가

src/features/received/model/useAddFolderModal.ts, src/features/received/model/useUpdateFolderModal.ts, src/features/received/ui/receivedCardView.tsx, src/shared/ui/Toast/sonner.tsx
=> [Fix] 버튼 클릭해도 폴더 추가, 수정 안되는 오류 수정

src/app/(detail)/card-detail/[cardId]/page.tsx, src/shared/providers/ApiErrorBoundary.tsx, src/shared/providers/GlobalErrorBoundary.tsx
에러 바운드리 파일명 임시 수정
에러 바운드리 파일명 임시 수정
에러 바운드리 파일명 임시 수정
=> refactor : 에러 바운드리 파일명 임시 수정

src/features/auth/login/ui/LoginButton.tsx
=> [refactor] apple login 정상화

src/app/(detail)/card-detail/[cardId]/page.tsx
=> [main] fix import error

src/app/(received)/received/interesting/page.tsx, src/features/received/model/queries/useInterestCardsQuery.ts, src/features/received/types/interestCards.ts, src/features/received/ui/receivedCard.tsx, src/features/received/ui/receivedCardView.tsx
흥미로운 명함 API 연동
흥미로운 명함 API 연동 완료
| 기능 | 스크린샷 |
| 받은 명함 페이지 | <img width="300" alt="image" src="https://github.com/user-attachments/assets/9c3f940b-23bd-4fa6-bee1-db7e2e2c95e0" /> |
| 흥미로운 명함 페이지| <img width="300" alt="image" src="https://github.com/user-attachments/assets/6b08c756-b918-456a-9540-220bb678c4b2" />|
- 받은 명함에서 배너는 흥미로운 명함이 있을 때만 나오게 됩니다.
=> [feat] 흥미로운 명함 API 연동 완료

src/app/(detail)/card-detail/[cardId]/page.tsx
=> 🐛 Hotfix: 파일 참조 에러 수정

src/app/(received)/received/choose/page.tsx, src/app/(received)/received/search/page.tsx, src/features/home/containers/CardContainer.tsx, src/features/received/ui/search/latestSearchKeyword.tsx, src/features/share/containers/QrContainer.tsx
#282 받은 명함 검색 오류 수정, 아래 스와이프 구현
- 최근 검색어에서 삭제 클릭 시, 이벤트 전파 오류 수정
- 공유 페이지에서 명함 아래로 스와이프하는 애니메이션 구현
- 명함 선택 - 폴더 설정 시, 토스트 두 개 뜨는 오류 수정
| 기능 | 스크린샷 |
| 아래로 공유 스와이프 | <video src="https://github.com/user-attachments/assets/ac2b671e-309d-49a3-b8cc-deed22f8179a" />  |
=> [Fix] 받은 명함 검색 오류 수정, 아래 스와이프 구현

src/features/auth/login/apis/getToken.ts, src/features/auth/login/utils/nativeBridge.ts, src/features/share/container/AnimatedShareCardWrapper.tsx, src/shared/hooks/useDevice.ts
=> [feat]딥링크 후 저장 로직 및 라우팅 수정, 소셜 로그인 웹뷰 브릿지 코드 적용

src/features/share/container/AnimatedShareCardWrapper.tsx, src/features/share/hooks/mutations/useSaveCard.ts, src/features/share/hooks/useCardDetail.ts, src/features/share/hooks/useCardShareAutoAction.ts, src/middleware.ts
=> [feat] 카드 공유 페이지 - 관심사 분리 훅 적용 및 딥링크 조건 개선

src/features/auth/login/apis/getToken.ts, src/features/auth/login/types/auth.ts
=> [fix] 로그인 웹뷰 푸시 토큰 파싱 로직 추가 및 로그인 요청 페이로드 수정

src/features/setting/ui/index.tsx, src/shared/utils/nativeBridge.ts
=> ✨ Feat: 문의사항 페이지 웹뷰 브릿지 추가

src/features/setting/hooks/useNotificationSettings.ts
=> [deploy] 알림 설정 최신값으로 전달 수정 및 배포

src/features/share/hooks/useCardShareAutoAction.ts
=> 🐛 Fix: 카드 공유 딥링크 개선

src/app/globals.css, src/features/card-notes/ui/memo/cardNotesMemoCard.tsx, src/features/card-notes/ui/select/cardNotesCard.tsx, src/features/home/containers/CardContainer.tsx
홈 화면 스와이프 적용
홈 화면 스와이프 적용
| 기능 | 스크린샷 |
https://github.com/user-attachments/assets/66d8edb6-e6be-4e76-83c6-809494551732
=> [feat] 홈 화면 스와이프 적용

src/app/(detail)/card-detail/[cardId]/page.tsx
=> 🐛 Fix: import 버그 수정

src/shared/ui/appbar.tsx
=> ✨ Feat: 흥미로운 명함, 한줄메모 뒤로가기 아이콘 웹뷰화면 최적화

src/features/home/containers/CardContainer.tsx, src/features/home/containers/DraggableCard.tsx
#312 
명함 위로 스와이프 할 때, 다른 명함 슬라이드도 위로 올라가는 이슈 해결
=> [Hotfix] 명함 생성 리로드, 스와이프 관련 이슈 해결

src/features/home/containers/CardContainer.tsx, src/features/home/containers/DraggableCard.tsx, src/shared/ui/appbar.tsx
=> [deploy] 명함 위로 스와이프 시 주변 명함도 같이 올라가는 오류 수정

src/features/auth/login/ui/LoginFeature.tsx
=> ♻️ Refactor: 카카오톡 주석

src/app/(create)/card-create/loading.tsx, src/app/(create)/card-create/new-card/loading.tsx, src/app/(create)/card-create/new-card/multi-step-form/loading.tsx, src/app/(detail)/card-detail/[cardId]/loading.tsx, src/app/(notes)/card-notes/loading.tsx, src/app/(notes)/card-notes/memo/loading.tsx, src/app/(received)/received/choose/loading.tsx, src/app/(received)/received/interesting/loading.tsx, src/app/(received)/received/loading.tsx, src/app/(received)/received/search/loading.tsx, src/app/(share)/card-share/[id]/loading.tsx, src/app/loading.tsx, src/app/login/loading.tsx, src/app/onboarding/loading.tsx, src/app/page.tsx, src/app/setting/alram-list/loading.tsx, src/app/setting/alram/loading.tsx, src/app/setting/loading.tsx, src/app/setting/privacy-terms/loading.tsx, src/app/setting/terms/loading.tsx, src/app/setting/user-quit/loading.tsx, src/app/share/loading.tsx, src/app/share/page.tsx, src/features/home/containers/CardContainer.tsx, src/features/home/containers/DraggableCard.tsx, src/features/home/containers/HeaderContainer.tsx, src/features/share/containers/SegmentContainer.tsx, src/shared/providers/GlobalErrorBoundary.tsx, src/shared/ui/appbar.tsx
#312 
- 페이지 이동 시 로딩 추가, 알림 페이지 라우팅 추가
- 명함 공유 페이지 탭바 텍스트 색상, 명함 공유 시 그라데이션 추가
- 로딩창
| 기능 | 스크린샷 |
=> [QA] QA 이것저것..

public/icons/infoIcon.svg, src/features/share/components/EmptyPeople.tsx, src/features/share/containers/NearbyCardShareContainer.tsx
=> [Feat] 주변 명함 emptycase 추가

src/app/page.tsx
=> 🚑️ Hotfix: 홈화면 페이드인 삭제

src/features/auth/login/ui/LoginFeature.tsx
=> 🚑️ Hotfix: 카카오 버튼 주석 해제

src/app/page.tsx, src/features/home/containers/HeaderContainer.tsx, src/features/onboarding/config/slides.tsx
* [✏️ Fix: 알림 리스트 라우팅 수정](https://github.com/depromeet/Took-FE/commit/9cad717576162006638b13dc5da9c367cc9a9fa7)
* [💄 Style: 메인페이지 백그라운드 중앙 정렬](https://github.com/depromeet/Took-FE/commit/939d89ef1f6ecf30e8a8a8ed2bca22a5110e39e8)
* [✏️ Fix: 온보딩 블루투스 텍스트 내주변으로 수정](https://github.com/depromeet/Took-FE/commit/00fd148f8888b9f38b156e75f97dc37db4cc6832)
| 기능 | 스크린샷 |
=> [fix] 알림 리스트 라우팅 수정, 온보딩 블루투스 텍스트 내주변으로 수정, 메인페이지 백그라운드 중앙 정렬
